version: '3'

services:
    rabbitmq:
        image: rabbitmq
        restart: unless-stopped
    cyberhead:
        build:
            context: .
        ports:
            - "127.0.0.1:80:80"
        depends_on:
            - rabbitmq
        restart: unless-stopped
        volumes:
            - ./CyberHead:/CyberHead
