version: '3'

services:
    mysql:
        image: mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: db
        ports:
          - "3306:3306"
        restart: unless-stopped
    redis:
        image: redis
        restart: unless-stopped
    rabbitmq:
        image: rabbitmq
        ports:
          - "5672:5672"
        restart: unless-stopped
    cyberhead:
        build:
            context: .
        image: cyberhead
        environment:
            CH_DB_NAME: db
            CH_DB_HOST: localhost
            CH_DB_USER: root
            CH_DB_PASSWORD: root
        volumes:
            - ..:/home/CyberHead
        working_dir:  /home/CyberHead
 
        ports:
            - "80:80"
        depends_on:
            - rabbitmq
            - mysql
            - redis
        links:
            - mysql:mysql
        command: tail -F anything
        restart: unless-stopped
