version: '3'

services:
    mysql:
        image: mysql
        restart: unless-stopped
    redis:
        image: redis
        restart: unless-stopped
    rabbitmq:
        image: rabbitmq
        restart: unless-stopped
    cyberhead:
        volumes:
            - ./CyberHead:/CyberHead
        build:
            context: .
        ports:
            - "127.0.0.1:80:80"
        depends_on:
            - rabbitmq
        restart: unless-stopped
